% test stimuli
% LED_pattern(stimu,file,pw)
% repeat white noise three times as pre test

close all
rate=20000;

path='\\192.168.1.102\Public\Retina\Chou\stimuli_data\20220822_stimuli\';
cd(path)
all_file = dir('*.mat');
parameters=cell(length(all_file)+3,3);
for i=1:length(all_file)+3
    parameters{i,1}='ld';
    parameters{i,3}=0;
end
for i=1:3
    parameters{i,2}=[path,'WhiteNoise_mean=10_C=0.2.mat'];
end
shuffled_ind=randperm(length(all_file));
for i=1:length(all_file)
    parameters{i+3,2}=[path,all_file(shuffled_ind(i)).name];
end

ccc=clock;
save(['\\192.168.1.102\Public\Retina\Chou\stimuli_data\sti_seq\stimuli_seq_',num2str(ccc(4)),num2str(ccc(5)),'.mat'])

% parameters=...   % input: {stimulation type, path, other parameter}
% {'ld',[path,'WhiteNoise_mean=10_C=0.2.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=0_mean=10_amp=2.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=13_C=0.1.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=13_C=0.2.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=13_C=0.3.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=13_C=0.05.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=4_C=0.3.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=4_C=0.2.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=4_C=0.1.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=4_C=0.05.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=10_C=0.3.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=10_C=0.1.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=10_C=0.2.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=10_C=0.05.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=1_C=0.3.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=1_C=0.2.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=1_C=0.1.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=1_C=0.05.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=7_C=0.3.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=7_C=0.2.mat'],0;... 
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=7_C=0.1.mat'],0;...
%     'ld',[path,'OU_tau=500ms_cutoff=1_mean=7_C=0.05.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=10_C=0.2.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=1_C=0.2.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=1_C=0.3.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=1_C=0.1.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=1_C=0.05.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=4_C=0.2.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=4_C=0.3.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=4_C=0.1.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=4_C=0.05.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=7_C=0.1.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=7_C=0.2.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=7_C=0.3.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=7_C=0.05.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=10_C=0.1.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=10_C=0.3.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=10_C=0.05.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=13_C=0.1.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=13_C=0.2.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=13_C=0.3.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=13_C=0.05.mat'],0;...
%     'ld',[path,'WhiteNoise_mean=10_C=0.2.mat'],0}; 


    
stimu_set=parameters(:,1); 
file_set=parameters(:,2);
pw_set=parameters(:,3);

%% generate total stimuli data
ey_total=[];
a2_total=[];
for i=1:length(stimu_set)
    stimu=stimu_set{i};
    file=file_set{i};
    pw=pw_set{i};
    
    [ey,a2,ss]=LED_pattern_chou(stimu,file,pw);
    close all
    ey_total=[ey_total ey zeros(1,300*20000)];
    a2_total=[a2_total a2 zeros(1,300*20000)];
    
end
tey_total=1/rate:1/rate:length(ey_total)/rate;
figure;subplot(2,1,1)
plot(tey_total,ey_total);
subplot(2,1,2)
ta2_total=1/rate:1/rate:length(a2_total)/rate;
plot(ta2_total,a2_total)

%% stimuli begin
for i=1:length(stimu_set)-1
    stimu=stimu_set{i}
    file=file_set{i}
    pw=pw_set{i}
    
    DAQ_LED_auto_chou
    
    pause(300)
end

stimu=stimu_set{length(stimu_set)}
file=file_set{length(stimu_set)}
pw=pw_set{length(stimu_set)}
DAQ_LED_auto_chou